branches:
  only:
    - master
    - develop
language: ruby
rvm:
  - 2.2.5
env:
  - REDMINE_VER=2.6.0 DB=mysql
  - REDMINE_VER=2.6.0 DB=postgresql
  - REDMINE_VER=3.0.0 DB=mysql
  - REDMINE_VER=3.0.0 DB=postgresql
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: 2.0.0
      env: REDMINE_VER=2.6.0 DB=mysql
    - rvm: 2.0.0
      env: REDMINE_VER=2.6.0 DB=postgresql
  exclude: # anyone is free to adopt a build, until then, no builds that don't have a maintainer

install: "echo skip bundle install"
before_script:
- sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS charts;'
  -U postgres; fi"
- sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database charts;' -U
  postgres; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS charts;';
  fi"
script:
  - export RAILS_ENV=test
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_charts
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - export PATH_TO_TESTER=`pwd`/redmine_tester.sh
  - mkdir $TESTSPACE
  - cp config/database.yml.${DB} $TESTSPACE/database.yml
  - bash -x ./redmine_install.sh -c
  - bash -x ./redmine_install.sh -i
  - bash -x ./redmine_install.sh -t
  - bash -x ./redmine_install.sh -u
